version: 2.1
orbs:
  mailer-orb: "sudiptog81/mailer-orb@1.0.0"
workflows:
  use-my-orb:
    jobs:
      - mailer-orb/mail:
          body: |-
            Sample Mail
            Regards,
            Circle CI
          from: admin@ghosh.pro
          subject: Example mail from mailer-orb
          to: sudipto@ghosh.pro