version: 2.1
orbs:
  mailer-orb: "sudiptog81/mailer-orb@1.0.0"
workflows:
  use-my-orb:
    jobs:
      - mailer-orb/mail:
          context: email 
          body: |-
            Sample Mail
            Regards,
            Circle CI
          from: rajpurohitarvindsingh@gmail.com
          subject: Example mail from mailer-orb
          to: rajpurohitarvindsingh@gmail.com